name: Deploy Docker Container

on:
  push:
    branches:
      - main  # main 브랜치로 푸시될 때마다 배포

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 기반 환경에서 실행

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your_docker_image_name .
          docker push your_docker_image_name

      - name: SSH to server and run Docker container
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no username@${{ secrets.SERVER_IP }} "
            docker pull your_docker_image_name &&
            docker run -d -p 5000:5000 --name your_container_name your_docker_image_name
          "
