name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 기반 환경에서 실행

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yunabyte/babpat-ai .
          docker push yunabyte/babpat-ai

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH to server and run Docker container
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            echo \"${{ secrets.DOCKER_PASSWORD }}\" | docker login --username \"${{ secrets.DOCKER_USERNAME }}\" --password-stdin &&
            docker pull yunabyte/babpat-ai &&
            docker rm -f babpat-ai || true &&
            docker run -d -p 8000:8000 --name babpat-ai \
              -e DB_HOST=${DB_HOST} \
              -e DB_NAME=${DB_NAME} \
              -e DB_USER=${DB_USER} \
              -e DB_PASSWORD=${DB_PASSWORD} \
              -e OPENAI_API_KEY=${OPENAI_API_KEY} \
              yunabyte/babpat-ai
          "